apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Release.Name }}
  service:
    name: {{ .Release.Name }}
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /*
      methods: ["GET", "POST", "PUT", "DELETE"]
      noAuth: true