apiVersion: v1
kind: Config
clusters:
- name: kyma
  cluster:
    server: https://api.c-4fd872e.kyma.ondemand.com
    insecure-skip-tls-verify: true

users:
- name: github-actions
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im10ZUF2M3diQ2pUbi1OOC1KUFM4S0RBdmdEZGp4aHdVNXd3UnFKV1pYcUEifQ.eyJhdWQiOlsia3ViZXJuZXRlcyIsImdhcmRlbmVyIl0sImV4cCI6MTc3NTAyNzIwNCwiaWF0IjoxNzc1MDIzNjA0LCJpc3MiOiJodHRwczovL2FwaS5jLTRmZDg3MmUua3ltYS5pbnRlcm5hbC5saXZlLms4cy5vbmRlbWFuZC5jb20iLCJqdGkiOiJkZjU0MDc2Zi01ZDllLTQ2ZDUtOGEyNC02ZmI5MmIyOWFiOWYiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlZmF1bHQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ2l0aHViLWFjdGlvbnMta3ltYSIsInVpZCI6ImNlMGZmYzI3LWYwODctNGRhYi05ZDMzLTVhZmM1MzU2MWFiZCJ9fSwibmJmIjoxNzc1MDIzNjA0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpnaXRodWItYWN0aW9ucy1reW1hIn0.Ip31TN5oh-lujiWMmUX8K0tCxi7zALF3FPtmMavyNq6sOcvtLgvG77HU2gT22546NI23FGwmLhSTPIR1erXMoCpBPkVyjNOghLNOg3WouTNknusD8vhH--GQViiGM-uImyPntZbQamgj0fX7NrGkfYPraRJ06Ui5ZtVzpJ2PgnzI8tNI6sPxOtbZJflh-Yi4zHVToP8w_NBynUELxvoMSxemGcqLHMOcar7WAciBT3UE9KoSeveoXLltM-vcuX35fDXERNy-kPGVnDRMwXFcwGL5cIWXxaDU4QTHNaf1QMQyygoFF03Oj5rosN51MZEFwNTkD682t9Na8LJHXdzqxzQIFCpUURD2AQiSpbZJkDGtY87ud7F3Gt_k2aFJi8HBlCEDqEyeWg_Av5xGTe1B95uSPRIGlVv8rH2BRsAg7m69j5R66apVZr0w6hlcZpUwkjMJ0CgWuaSPeMh2RQisxTjSEyhjv37Ab7H63pThPuDmqhsA4x35sXPbgp17_r06zF8geCIMUimA6hlk_w9Fp33t-2s84gYWAnltJYTYEtTKmc-xDQ23qAE496pL3_t_b-4Sc0nDFeNnV48SUDPlx6ijrD6od89XHFZ-KYFjqyNhHRUz_89A_1mKBCaWeBHqaHnKkfSxJEGrAgWrgi1av2Kv6s5aKpuipHzYV_NzptQ

contexts:
- name: kyma-context
  context:
    cluster: kyma
    user: github-actions-kyma

current-context: kyma-context